### ISSUE TITLE
Can't flash ODM image

### ISSUE THREAD

**Issue by abioteau** [sonyxperiadev/device-sony-suzu#34]
$ fastboot getvar all
(bootloader) version:0.5
(bootloader) max-download-size:	0x20000000
(bootloader) partition-type:cache:ext4
(bootloader) partition-size:cache:	 0x10000000
(bootloader) partition-type:userdata:ext4
(bootloader) partition-size:userdata:	 0x52cc00000
(bootloader) partition-type:system:ext4
(bootloader) partition-size:system:	 0x1d3800000
(bootloader) secure:no
(bootloader) version-baseband:1300-4911_34.0.A.1.267
(bootloader) version-bootloader:1299-4841 S1_Boot_MSM8956_LA1.0.1_68-B
(bootloader) serialno:CB512A0H5P
(bootloader) product:F5121
all: 
finished. total time: 0.015s
$ fastboot flash oem SW_binaries_for_Xperia_AOSP-N_MR1_4.4_v03-loire.img
target reported max download size of 536870912 bytes
sending 'oem' (206099 KB)...
OKAY [  7.987s]
writing 'oem'...
FAILED (remote: Command not allowed)
finished. total time: 7.990s

How enable flashing of OEM partition?

**Comment by jerpelea** [comment]
You have tu update the bootloader to be able to flash the oem partition 

The minimum firmware version is 34.3.A.0.228 

Please update your device with flashtool
https://developer.sonymobile.com/open-devices/flash-tool/

**Comment by abioteau** [comment]
Effectively, with new bootloader it works !!!

$ fastboot getvar all
(bootloader) version:0.5
(bootloader) max-download-size:	0x20000000
(bootloader) partition-type:cache:ext4
(bootloader) partition-size:cache:	 0x10000000
(bootloader) partition-type:userdata:ext4
(bootloader) partition-size:userdata:	 0x52cc00000
(bootloader) partition-type:system:ext4
(bootloader) partition-size:system:	 0x1d3800000
(bootloader) secure:no
(bootloader) version-baseband:1300-4911_34.3.A.0.217
(bootloader) version-bootloader:**1299-4841 S1_Boot_MSM8956_LA1.0.1_N_164**
(bootloader) serialno:CB512A0H5P
(bootloader) product:F5121
