### ISSUE TITLE
Camera not working in latest 7.1.1 builds.

### ISSUE THREAD

**Issue by tswindell** [sonyxperiadev/device-sony-suzu#43]
Looks like the camera subsystem can't open the configuration file that was recently moved under vendor. Not sure where to patch this to submit pull request.

mm-camera: <SENSOR>< INFO> 341: sensor_init_xml_probe: Cannot read file from /system/etc/camera/camera_config.xml. read failed

**Comment by bartcubbins** [comment]
Did you flash the latest blobs?
https://developer.sony.com/file/download/software-binaries-for-aosp-nougat-android-7-1-kernel-4-4-loire/

**Comment by jerpelea** [comment]
please post issues in the bug tracker
